
#' Simulate sediment accumulation
#'
#' @param max_age The maximum age of the simulation (years)
#' @param time_step The time to consider in each step (years)
#' @param mass_accumulation A function such as that generated by [pb210_mass_accumulation_constant()].
#'   Values returned by the function should be in kg / m^2^ / year.
#' @param compressibility A function such as that generated by [pb210_compressibility_constant()].
#'   Values returned by the function should be in 1 / Pa.
#' @param density A function such as that generated by [pb210_density_constant()].
#'   Values returned by the function should be in kg / m^3^.
#' @param water_content A function such as that generated by [pb210_water_content_constant()].
#'   Values returned by the function should be in mass water / mass sample (unitless between 0 and 1).
#'
#' @return A tibble with components ...
#' @importFrom rlang .data
#' @export
#'
#' @examples
#' pb210_simulate_accumulation()
#'
pb210_simulate_accumulation <- function(max_age = 300, time_step = 1,
                                        mass_accumulation = pb210_mass_accumulation_constant(),
                                        compressibility = pb210_compressibility_constant(),
                                        density = pb210_density_constant(),
                                        water_content = pb210_water_content_constant()) {
  stopifnot(
    is.numeric(max_age), length(max_age) == 1,
    is.numeric(time_step), length(time_step) == 1, time_step > 0,
    is.function(mass_accumulation),
    is.function(compressibility),
    is.function(density),
    is.function(water_content)
  )

  tbl <- tibble::tibble(
    age_top = seq(max_age - time_step, 0, by = -time_step),
    age_bottom = seq(max_age, 0 + time_step, by = -time_step)
  )

  tbl
}

#' Simulate a core of an accumulation
#'
#' @param age_simulation An age simulation, created by [pb210_simulate_accumulation()].
#' @param depth_step A vector of depth steps to consider, from the top to the bottom
#'   of the core. There should be one element in the vector for each slice considered.
#' @param core_area The area of the corer, in m^2^.
#'
#' @return A tibble with components ...
#' @export
#'
#' @examples
#' pb210_simulate_core()
#'
pb210_simulate_core <- function(age_simulation = pb210_simulate_accumulation(),
                                depth_step = rep(0.5, 60),
                                core_area = pb210_core_area()) {
  stopifnot(
    tibble::is_tibble(age_simulation), all(c() %in% colnames(age_simulation)),
    is.numeric(core_area), length(core_area) == 1, core_area > 0
  )

  tibble::tibble(
    depth_top = c(0, cumsum(depth_step[-1])),
    depth_bottom = cumsum(depth_step)
  )
}

#' Parameter generators for mass accumulation rates
#'
#' @param value,mean,initial An accumulation rate, in kg / m2 / year.
#' @param sd For random normal accumulation rates, the standard deviation
#' @param mean_slope,sd_slope The mean and standard deviation of the change in
#'   slope, in kg / m2 / year / year
#'
#' @return A function of a single parameter, `age`, which is a (decreasing) vector of ages.
#' @export
#'
#' @examples
#' age_compare <- tibble::tibble(
#'   ages = 150:0,
#'   constant = pb210_mass_accumulation_constant()(ages),
#'   rnorm = pb210_mass_accumulation_rnorm()(ages),
#'   rnorm_trend = pb210_mass_accumulation_rnorm_trend()(ages)
#' )
#'
pb210_mass_accumulation_constant <- function(value = 0.150)  {
  force(value)
  function(age) {
    value
  }
}

#' @rdname pb210_mass_accumulation_constant
#' @export
pb210_mass_accumulation_rnorm <- function(mean = 0.150, sd = 0.020) {
  force(mean)
  force(sd)
  function(age) {
    stats::rnorm(length(age), mean = 150, sd = 20)
  }
}

#' @rdname pb210_mass_accumulation_constant
#' @export
pb210_mass_accumulation_rnorm_trend <- function(initial = 0.150, mean_slope = 0, sd_slope = 0.005) {
  force(initial)
  force(mean_slope)
  force(sd_slope)
  function(age) {
    delta_accumulation <- stats::rnorm(
      length(age) - 1,
      mean = -diff(age) * mean_slope,
      sd = -diff(age) * sd_slope
    )

    cumsum(c(initial, delta_accumulation))
  }
}

#' Parameter generators for density values
#'
#' Note that this refers to dry density at the time of deposition.
#'
#' @param value A density at the time of deposition, in kg / m3
#'
#' @return A function of a single parameter, `age`, which is a (decreasing) vector of ages.
#' @export
#'
#' @examples
#' ages <- 150:0
#' pb210_density_constant()(ages)
#'
pb210_density_constant <- function(value = 1500)  {
  force(value)
  function(age) {
    value
  }
}

#' Parameter generators for water content
#'
#' Note that this refers to water content at the time of deposition.
#'
#' @param value A water content at the time of deposition, unitless (mass water / mass sample)
#'
#' @return A function of a single parameter, `age`, which is a (decreasing) vector of ages.
#' @export
#'
#' @examples
#' ages <- 150:0
#' pb210_water_content_constant()(ages)
#'
pb210_water_content_constant <- function(value = 0.95)  {
  force(value)
  function(age) {
    value
  }
}

#' Parameter generators for compressibility
#'
#' Note that this refers to compressibility at the time of deposition.
#'
#' @param value A compressibility at the time of deposition, in 1/Pa.
#'   Lower values indicate a higher propensity for the material to be compressed.
#'
#' @return A function of a single parameter, `age`, which is a (decreasing) vector of ages.
#' @export
#'
#' @examples
#' ages <- 150:0
#' pb210_compressibility_constant()(ages)
#'
pb210_compressibility_constant <- function(value = 2e-6)  {
  force(value)
  function(age) {
    value
  }
}
