
#' Simulate sediment accumulation
#'
#' @param max_age The maximum age of the simulation (years)
#' @param time_step The time to consider in each step (years)
#' @param supply A function such as that generated by [pb210_supply_constant()].
#'   The flux of lead-210 to the surface, in Bq/ m^2^ / year
#' @param mass_accumulation A function such as that generated by [pb210_mass_accumulation_constant()].
#'   Values returned by the function should be in kg / m^2^ / year.
#' @param compressibility A function such as that generated by [pb210_compressibility_constant()].
#'   Values returned by the function should be in 1 / Pa.
#' @param initial_density A function such as that generated by [pb210_density_constant()].
#'   Values returned by the function should be in kg / m^3^.
#' @param decay_constant The decay constant to use (see [pb210_decay_constant()])
#'
#' @return A tibble with components ...
#' @importFrom rlang .data
#' @export
#'
#' @examples
#' pb210_simulate_accumulation()
#'
pb210_simulate_accumulation <- function(mass_accumulation = pb210_mass_accumulation_constant(),
                                        supply = pb210_supply_constant(),
                                        compressibility = pb210_compressibility_constant(),
                                        initial_density = pb210_density_constant(),
                                        decay_constant = pb210_decay_constant(),
                                        max_age = 300, time_step = 5) {
  stopifnot(
    is.numeric(max_age), length(max_age) == 1,
    is.numeric(time_step), length(time_step) == 1, time_step > 0,
    is.function(supply),
    is.function(mass_accumulation),
    is.function(compressibility),
    is.function(initial_density)
  )

  tbl <- tibble::tibble(
    # ages
    age_top = seq(max_age - time_step, 0, by = -time_step),
    age_bottom = seq(max_age, 0 + time_step, by = -time_step),
    age = (.data$age_top + .data$age_bottom) / 2,

    # initial values
    initial_pb210_content = supply(.data$age) * time_step, # Bq
    slice_mass = mass_accumulation(.data$age) * time_step, # kg
    compressibility = compressibility(.data$age), # 1/Pa
    initial_density = initial_density(.data$age), # kg / m^3

    # radioactive decay of pb210, normalize to mass
    pb210_activity = .data$initial_pb210_content * exp(-decay_constant * .data$age) / .data$slice_mass, # Bq / kg

    # compression of sediment
    cumulative_mass_above = c(rev(cumsum(rev(.data$slice_mass[-1]))), 0), # kg
    delta_pressure = 9.806 * .data$cumulative_mass_above, # Pa
    relative_volume = 1 - (.data$delta_pressure * .data$compressibility), # unitless (volume / volume at deposition)

    # use density and relative_volume to map slice mass to thickness
    # kg / m^2 / (kg / m^3)
    thickness = .data$slice_mass / .data$initial_density * .data$relative_volume, # m
    depth_bottom = rev(cumsum(rev(.data$thickness))),
    depth_top = c(rev(cumsum(rev(.data$thickness[-1]))), 0),
    depth = (.data$depth_top + .data$depth_bottom) / 2
  )

  tbl[c("age", "depth", "pb210_activity", "age_top", "age_bottom", "depth_top", "depth_bottom", "cumulative_mass_above")]
}


#' Simulate a core of an accumulation
#'
#' @param age_simulation An age simulation, created by [pb210_simulate_accumulation()].
#' @param depth_step A vector of depth steps to consider, from the top to the bottom
#'   of the core. There should be one element in the vector for each slice considered.
#' @param core_area The area of the corer, in m^2^.
#'
#' @return A tibble with components ...
#' @export
#'
#' @examples
#' pb210_simulate_core()
#'
pb210_simulate_core <- function(age_simulation = pb210_simulate_accumulation(),
                                depth_step = rep(0.5, 60),
                                core_area = pb210_core_area()) {
  stopifnot(
    tibble::is_tibble(age_simulation), all(c() %in% colnames(age_simulation)),
    is.numeric(core_area), length(core_area) == 1, core_area > 0
  )

  tibble::tibble(
    depth_top = c(0, cumsum(depth_step[-1])),
    depth_bottom = cumsum(depth_step),
    depth = (.data$depth_top + .data$depth_bottom) / 2
  )
}

#' Parameter generators for lead-210 supply
#'
#' @param value An flux of lead 210, in Bq / m^2^ / year.
#'
#' @return A function of a single parameter, `age`, which is a (decreasing) vector of ages.
#' @export
#'
#' @references
#' Appleby, P.G. 2008. Three decades of dating recent sediments by fallout
#' radionuclides: a review. The Holocene, 18: 83–93. doi:10.1177/0959683607085598.
#'
#' @examples
#' ages <- 150:0
#'
pb210_supply_constant <- function(value = 100)  {
  force(value)
  function(age) {
    value
  }
}


#' Parameter generators for mass accumulation rates
#'
#' @param value,mean,initial An accumulation rate, in kg / m2 / year.
#' @param sd For random normal accumulation rates, the standard deviation
#' @param mean_slope,sd_slope The mean and standard deviation of the change in
#'   slope, in kg / m2 / year / year
#'
#' @return A function of a single parameter, `age`, which is a (decreasing) vector of ages.
#' @export
#'
#' @examples
#' age_compare <- tibble::tibble(
#'   ages = 150:0,
#'   constant = pb210_mass_accumulation_constant()(ages),
#'   rnorm = pb210_mass_accumulation_rnorm()(ages),
#'   rnorm_trend = pb210_mass_accumulation_rnorm_trend()(ages)
#' )
#'
pb210_mass_accumulation_constant <- function(value = 0.150)  {
  force(value)
  function(age) {
    value
  }
}

#' @rdname pb210_mass_accumulation_constant
#' @export
pb210_mass_accumulation_rnorm <- function(mean = 0.150, sd = 0.020) {
  force(mean)
  force(sd)
  function(age) {
    stats::rnorm(length(age), mean = 150, sd = 20)
  }
}

#' @rdname pb210_mass_accumulation_constant
#' @export
pb210_mass_accumulation_rnorm_trend <- function(initial = 0.150, mean_slope = 0, sd_slope = 0.005) {
  force(initial)
  force(mean_slope)
  force(sd_slope)
  function(age) {
    delta_accumulation <- stats::rnorm(
      length(age) - 1,
      mean = -diff(age) * mean_slope,
      sd = -diff(age) * sd_slope
    )

    cumsum(c(initial, delta_accumulation))
  }
}

#' Parameter generators for density values
#'
#' Note that this refers to dry density at the time of deposition.
#'
#' @param value A density at the time of deposition, in kg / m3
#'
#' @return A function of a single parameter, `age`, which is a (decreasing) vector of ages.
#' @export
#'
#' @examples
#' ages <- 150:0
#' pb210_density_constant()(ages)
#'
pb210_density_constant <- function(value = 150)  {
  force(value)
  function(age) {
    value
  }
}

#' Parameter generators for compressibility
#'
#' Note that this refers to compressibility at the time of deposition.
#'
#' @param value A compressibility at the time of deposition, in 1/Pa.
#'   Higher values (closer to 0) indicate a higher propensity for the material
#'   to be compressed.
#'
#' @return A function of a single parameter, `age`, which is a (decreasing) vector of ages.
#' @export
#'
#' @examples
#' ages <- 150:0
#' pb210_compressibility_constant()(ages)
#'
pb210_compressibility_constant <- function(value = 1e-3)  {
  force(value)
  function(age) {
    value
  }
}
